springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

timetablemanager:
  allowed-origin: http://localhost:3000